linters:
  enable:
    - revive # Replacing deprecated golint
    - gofmt
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign
    - unconvert
    - misspell
    - goimports
    - prealloc
    - gosec

linters-settings:
  goimports:
    local-prefixes: github.com/CreativeUnicorns/userprefs

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0