services:
  postgres_userprefs_example:
    image: postgres:15
    container_name: postgres_userprefs_example
    environment:
      POSTGRES_USER: userprefs_user
      POSTGRES_PASSWORD: userprefs_password
      POSTGRES_DB: userprefs_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis_userprefs_example:
    image: redis:alpine
    container_name: redis_userprefs_example
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
